symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # Durée de validité du token (en secondes) - 1 heure
    lifetime: 3600
    # Nombre maximum de tentatives avant de devoir attendre
    throttle_limit: 5
